server/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/' , function() { return view('welcome'); });

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => 'auth'], function() {

	Route::get('/home', 'HomeController@index');
	Route::resource('/role', 'RoleController');
	Route::resource('/permission', 'PermissionController');
	Route::resource('/user', 'UserController');
	Route::resource('/module', 'ModuleController');
});

server/app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Permission;
use App\Models\Module;
use Illuminate\Http\Request;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::all();
        return view('admin.permission.index',compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $modules = Module::all();
        return view('admin.permission.create',compact('modules'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $permission = Permission::create($request->all());
         $permission->modules()->sync($request->module_id);
         return redirect()->route('permission.index')->withMessage('Permission successfuly added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = Permission::find($id);
        $modules = Module::all();
        $module_permission = $permission->modules()->pluck('id','id')->toArray();
        return view('admin.permission.edit',compact('permission','modules','module_permission'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $permission = Permission::find($id);
        $permission->update($request->all());
        $permission->modules()->sync($request->module_id);
        return redirect()->route('permission.index')->withMessage('Permission successfuly updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Permission::destroy($id);
        return redirect()->route('permission.index')->withMessage('Permission successfuly deleted');
    }
}

server/resources/views/admin/permission/create.blade.php
@extends('layouts.metronic')

@section('content')
	<form action="{{ route('permission.store') }}" method="POST">
	{{ csrf_field ()}}
	<legend>Create Permission</legend>
		<div class="form-group"> 
			<input class="form-control" type="text" name="name" placeholder="Name">
		</div>
		<div class="form-group"> 
			<input class="form-control" type="text" name="display_name" placeholder="Display Name" >
		</div>
		<div class="form-group"> 
			<input class="form-control" type="text" name="description" placeholder="Descritpion" >
		</div>
	   <div class="form-group"> 
			<h3>Module</h3>
			<select name="module_id" class="form-control">
			@foreach($modules as $module)
				<option value="{{ $module->id }}">{{ $module->name }}</option>
			@endforeach	
		    </select>	
		</div>
		<div>
			<input type="submit" value="Submit" class="btn btn-success">
		</div>
	</form>
@endsection

server/resources/views/admin/permission/edit.blade.php
@extends('layouts.metronic')

@section('content')
	<form action="{{ route('permission.update',$permission->id) }}" method="POST">
	{{ csrf_field ()}}
	{{ method_field('PATCH')}}
	<legend>Edit Permission</legend>
		<div class="form-group"> 
			<input class="form-control" type="text" name="name" placeholder="Name" value="{{ $permission->name }}">
		</div>
		<div class="form-group"> 
			<input class="form-control" type="text" name="display_name" placeholder="Display Name" value="{{ $permission->display_name }}" >
		</div>
		<div class="form-group"> 
			<input class="form-control" type="text" name="description" placeholder="Descritpion" value="{{ $permission->description }}" >
		</div>
		
	   <div class="form-group"> 
			<h3>Module</h3>
			<select name="module_id" class="form-control">
			@foreach($modules as $module)
				<option  {{in_array($module->id,$module_permission)?"selected":"" }}  value="{{ $module->id }}">{{ $module->name }}</option>
			@endforeach	
		    </select>	
		</div>
		<div>
			<input type="submit" value="Submit" class="btn btn-success">
		</div>
	</form>
@endsection

server/resources/views/admin/permission/index.blade.php
@extends('layouts.metronic')

@section('content')
  {{ session('message') }}
	<h3>Permisssion</h3>
	<a href="{{ route('permission.create') }}" class="btn btn-success" >Create Permission</a>
	<br><br>
	<table width="100%" class="table">
		<thead>
		<tr>
			<th>Name</th>
			<th>Display Name</th>
			<th>Description</th>
			<th>Action</th>
		 </tr>
		</thead>
		<tbody>
		@forelse($permissions as $permission)
		<tr>
			<td>{{ $permission->name }}</td>
			<td>{{ $permission->display_name }}</td>
			<td>{{ $permission->description }}</td>
			<td>
				<a href="{{ route('permission.edit',$permission->id) }}" class="btn btn-info btn-sm" >Edit</a>
				<form action="{{ route('permission.destroy',$permission->id) }}" method="post">
				{{ csrf_field() }}
				{{ method_field('DELETE') }}
				<input class="btn btn-sm btn-danger" type="Submit" value="DELETE">
				</form>
			</td>
		</tr>
		@empty
			<td colspan="3">No Roles</td>
		@endforelse
		</tbody>
	</table>
@endsection