server/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/' , function() { return view('welcome'); });

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => 'auth'], function() {

	Route::get('/home', 'HomeController@index');
	Route::resource('/role', 'RoleController');
	Route::resource('/permission', 'PermissionController');
	Route::resource('/user', 'UserController');
	Route::resource('/module', 'ModuleController');
});

server/app/Http/Controllers/ModuleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Module;
use Illuminate\Http\Request;

class ModuleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $modules = Module::all();
        return view('admin.module.index',compact('modules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.module.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Module::create($request->except(['_token']));
        return redirect()->route('module.index')->withMessage('Module successfuly added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $module = Module::find($id);
        return view('admin.module.edit',compact('module'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $module = Module::find($id);
         $module->update($request->all());
         return redirect()->route('module.index')->withMessage('Module successfuly updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Module::destroy($id);
       return redirect()->route('module.index')->withMessage('Module successfuly deleted');
    }
}

server/resources/views/admin/module/create.blade.php
@extends('layouts.metronic')

@section('content')
	<form action="{{ route('module.store') }}" method="POST">
	{{ csrf_field ()}}
	<legend>Create Module</legend>
		<div class="form-group"> 
			<input class="form-control" type="text" name="name" placeholder="Module Name">
		</div>
		<div class="form-group"> 
			<input class="form-control" type="text" name="description" placeholder="Description" >
		</div>
		<div>
			<input type="submit" value="Submit" class="btn btn-success">
		</div>
	</form>
@endsection

server/resources/views/admin/module/edit.blade.php
@extends('layouts.metronic')

@section('content')
	<form action="{{ route('module.update',$module->id) }}" method="POST">
	{{ csrf_field ()}}
	{{ method_field('PATCH')}}
	<legend>Update Module</legend>
		<div class="form-group"> 
			<input class="form-control" type="text" name="name" placeholder="Module Name" value="{{ $module->name }}">
		</div>
		<div class="form-group"> 
			<input class="form-control" type="text" name="description" placeholder="Description" value="{{ $module->description }}" >
		</div>
		<div>
			<input type="submit" value="Submit" class="btn btn-success">
		</div>
	</form>
@endsection

server/resources/views/admin/module/index.blade.php
@extends('layouts.metronic')

@section('content')
  {{ session('message') }}
	<h3>Modules</h3>
	<a href="{{ route('module.create') }}" class="btn btn-success" >Create Module</a>
	<br><br>
	<table width="100%" class="table">
		<thead>
		<tr>
			<th>Name</th>
			<th>Action</th>
		 </tr>
		</thead>
		<tbody>
		@forelse($modules as $module)
		<tr>
			<td>{{ $module->name }}</td>
			<td>{{ $module->description }}</td>
			<td>
				<a href="{{ route('module.edit',$module->id) }}" class="btn btn-info btn-sm" >Edit</a>
				<form action="{{ route('module.destroy',$module->id) }}" method="post">
				{{ csrf_field() }}
				{{ method_field('DELETE') }}
				<input class="btn btn-sm btn-danger" type="Submit" value="DELETE">
				</form>
			</td>
		</tr>
		@empty
			<td colspan="3">No Modules</td>
		@endforelse
		</tbody>
	</table>
@endsection