server/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/' , function() { return view('welcome'); });

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => 'auth'], function() {

	Route::get('/home', 'HomeController@index');
	Route::resource('/role', 'RoleController');
	Route::resource('/permission', 'PermissionController');
	Route::resource('/user', 'UserController');
	Route::resource('/module', 'ModuleController');
});

server/app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\Permission;
use App\Models\Module;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
        return view('admin.role.index',compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $modules = Module::all();
        return view('admin.role.create',compact('modules'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $role = Role::create($request->except(['permission','_token']));
        $role->perms()->sync($request->permission);
        return redirect()->route('role.index')->withMessage('Role successfuly added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $modules = Module::all();
        $permissions = Permission::all();
        $role_permissions = $role->perms()->pluck('id','id')->toArray();
        return view('admin.role.edit',compact('role','permissions','role_permissions','modules'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::find($id);

        $role->update($request->all());
        $role->perms()->sync($request->permission);
        return redirect()->route('role.index')->withMessage('Role successfully updated');

        // var_dump($request->permission);
/*        $role->update($request->all());
        $role->perms()->sync($request->permission);
        return redirect()->route('role.index')->withMessage('Role successfully updated');*/
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Role::destroy($id);
        return redirect()->route('role.index')->withMessage('Role successfuly deleted');
    }
}

server/resources/views/admin/role/create.blade.php
@extends('layouts.metronic')

@section('content')
	<form action="{{ route('role.store') }}" method="POST">
	{{ csrf_field ()}}
	<legend>Create Role</legend>
		<div class="form-group"> 
			<input class="form-control" type="text" name="name" placeholder="Role Name">
		</div>
		<div class="form-group"> 
			<input class="form-control" type="text" name="display_name" placeholder="Display Name" >
		</div>
		<div class="form-group"> 
			<input class="form-control" type="text" name="description" placeholder="Description" >
		</div>
		<div class="form-group"> 
			<h3>Module Permission</h3>
			<table class="table">
				@forelse($modules as $module)
					<tr>
						<td colspan="2"><h4>{{ $module->name }}</h4></td>	
					</tr>
					@foreach($module->permissions as $permission)
					 <tr>
						<td class="checkbox">
							<label><input type="checkbox" name="permission[]" value={{ $permission->id }}>{{ $permission->name }} </label>	
						</td>
					 </tr>
					 @endforeach	
		          @empty
		         <tr>
					<td colspan="3">No Module</td>
				</tr>
			    @endforelse	
			</table>
		</div>
		<div>
			<input type="submit" value="Submit" class="btn btn-success">
		</div>
	</form>
@endsection

server/resources/views/admin/role/edit.blade.php
@extends('layouts.metronic')

@section('content')
	<form action="{{ route('role.update',$role->id) }}" method="POST">
	{{ csrf_field ()}}
	{{ method_field('PATCH')}}
	<legend>Edit Role</legend>
		<div class="form-group"> 
			<input class="form-control" type="text" name="name" placeholder="Role Name" value="{{ $role->name }}">
		</div>
		<div class="form-group"> 
			<input class="form-control" type="text" name="display_name" placeholder="Display Name" value="{{ $role->display_name }}"  >
		</div>
		<div class="form-group"> 
			<input class="form-control" type="text" name="description" placeholder="Description" value="{{ $role->description }}" >
		</div>
				<div class="form-group"> 
			<h3>Module Permission</h3>
			<table class="table">
				@forelse($modules as $module)
					<tr>
						<td colspan="2"><h4>{{ $module->name }}</h4></td>	
					</tr>
					@foreach($module->permissions as $permission)
					 <tr>
						<td class="checkbox">
							<label><input  {{in_array($permission->id,$role_permissions)?"checked":"" }} type="checkbox" name="permission[]" value={{ $permission->id }}>{{ $permission->name }} </label>	
						</td>
					 </tr>
					 @endforeach	
		         @empty
		         <tr>
					<td colspan="3">No Module</td>
				</tr>
				@endforelse		
			</table>
		</div>
		<div>
			<input type="submit" value="Submit" class="btn btn-success">
		</div>
	</form>
@endsection

server/resources/views/admin/role/index.blade.php
@extends('layouts.metronic')

@section('content')
  {{ session('message') }}
	<h3>ROLE</h3>
	<a href="{{ route('role.create') }}" class="btn btn-success" >Create Role</a>
	<br><br>
	<table width="100%" class="table">
		<thead>
		<tr>
			<th>Name</th>
			<th>Display Name</th>
			<th>Description</th>
			<th>Action</th>
		 </tr>
		</thead>
		<tbody>
		@forelse($roles as $role)
		<tr>
			<td>{{ $role->name }}</td>
			<td>{{ $role->display_name }}</td>
			<td>{{ $role->description }}</td>
			<td>
				<a href="{{ route('role.edit',$role->id) }}" class="btn btn-info btn-sm" >Edit</a>
				<form action="{{ route('role.destroy',$role->id) }}" method="post">
				{{ csrf_field() }}
				{{ method_field('DELETE') }}
				<input class="btn btn-sm btn-danger" type="Submit" value="DELETE">
				</form>
			</td>
		</tr>
		@empty
			<td colspan="3">No Roles</td>
		@endforelse
		</tbody>
	</table>
@endsection